In [ ]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
plt.rcParams["animation.html"] = "jshtml"
matplotlib.rcParams['animation.embed_limit'] = 2**128

import numpy as np
import pandas as pd
import seaborn as sns
sns.set()

import time
import datetime

from Models.Fire import Fire
from Models.Firefighter import Firefighter
from Models.FireRescueModel import FireRescueModel

model = FireRescueModel(strategy="intelligent")

ITERATIONS = 100
i = 0

while not(model.defeat()) and not(model.victory()) and i < ITERATIONS:
    model.step()
    i += 1

if (model.victory()):
    print("Players won")
elif (model.defeat()):
    print("Players Lost")
    print("Damage: ", model.damageTokens)
    print("Victims Lost: ", model.victimsLost)
else:
    print("Times up")

allAgentsInfo = model.datacollector.get_agent_vars_dataframe()
allAgentsInfo.info()

allGrids = model.datacollector.get_model_vars_dataframe()
allGrids.info()

# fig, axs = plt.subplots(figsize = (4, 4))
# axs.set_xticks([])
# axs.set_yticks([])
# patch = plt.imshow(allGrids.iloc[0, 0], cmap = plt.cm.binary)

# def animate(i):
#     patch.set_data(allGrids.iloc[i, 0])

# anim = animation.FuncAnimation(fig, animate, frames = model.steps)

# anim

Could not import SolaraViz. If you need it, install with 'pip install --pre mesa[viz]'
move (6, 1)
move (1, 0)
move (0, 6)
move (1, 0)
move (6, 1)
move (0, 6)
move (0, 6)
move (1, 0)
move (6, 1)
move (0, 6)
move (1, 0)
move (6, 1)
move (0, 6)
move (1, 0)
move (6, 1)
move (1, 0)
move (0, 6)
move (6, 1)
move (0, 6)
move (6, 1)
move (1, 0)
move (1, 0)
move (1, 1)
move (2, 1)
move (3, 1)
move (4, 1)
move (5, 1)
It was not a victim :(
move (5, 2)
move (6, 1)
move (0, 6)
move (6, 1)
move (5, 3)
move (6, 3)
move (6, 4)
move (0, 6)
Times up
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 60 entries, (np.int64(1), np.int64(1)) to (np.int64(10), np.int64(2))
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Position  60 non-null     object
dtypes: object(1)
memory usage: 1.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Steps           10 non-null     int64
 1   VictimsRescued  10 non-null     int64
 2   VictimsLost     10 non-null     int64
 3   NewFire         10 non-null     object
 4   Dices           10 non-null     object
 5   DamageTokens    10 non-null     int64
 6   ChangedPOIs     10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

In [ ]:
result = pd.DataFrame(allGrids)
result

,Steps,VictimsRescued,VictimsLost,NewFire,Dices,DamageTokens,ChangedPOIs
0,0,0,0,[],"{'red': 5, 'black': 4}",0,[]
1,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}]","{'red': 2, 'black': 4}",0,[]
2,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 4}",0,[]
3,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 1}",0,[]
4,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 5}",0,[]
5,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 3}",0,[]
6,0,0,1,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 3}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
7,0,0,1,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 2}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
8,0,0,1,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 5}",6,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
9,0,0,1,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 0}",6,"[{'position': (2, 4), 'Rescued': False, 'Victi..."

:

:

:

:

:

:

:

:

:

:

In [ ]:
result

,Steps,VictimsRescued,VictimsLost,NewFire,Dices,DamageTokens,ChangedPOIs
0,0,0,0,[],"{'red': 5, 'black': 4}",0,[]
1,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}]","{'red': 2, 'black': 4}",0,[]
2,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 4}",0,[]
3,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 1}",0,[]
4,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 5}",0,[]
5,0,0,0,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 3}",0,[]
6,0,0,1,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 3}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
7,0,0,1,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 2}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
8,0,0,1,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 5}",6,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
9,0,0,1,"[{'position': (1, 2), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 0}",6,"[{'position': (2, 4), 'Rescued': False, 'Victi..."

:

:

:

:

:

:

:

:

:

: