In [1]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
plt.rcParams["animation.html"] = "jshtml"
matplotlib.rcParams['animation.embed_limit'] = 2**128

import numpy as np
import pandas as pd
import seaborn as sns
sns.set()

import time
import datetime

from Models.Fire import Fire
from Models.Firefighter import Firefighter
from Models.FireRescueModel import FireRescueModel

model = FireRescueModel(strategy="intelligent")

ITERATIONS = 1000
i = 0

while not(model.defeat()) and not(model.victory()) and i < ITERATIONS:
    model.step()
    i += 1

if (model.victory()):
    print("Players won")
elif (model.defeat()):
    print("Players Lost")
    print("Damage: ", model.damageTokens)
    print("Victims Lost: ", model.victimsLost)
else:
    print("Times up")

allAgentsInfo = model.datacollector.get_agent_vars_dataframe()
allAgentsInfo.info()

allGrids = model.datacollector.get_model_vars_dataframe()
allGrids.info()

# fig, axs = plt.subplots(figsize = (4, 4))
# axs.set_xticks([])
# axs.set_yticks([])
# patch = plt.imshow(allGrids.iloc[0, 0], cmap = plt.cm.binary)

# def animate(i):
#     patch.set_data(allGrids.iloc[i, 0])

# anim = animation.FuncAnimation(fig, animate, frames = model.steps)

# anim

Could not import SolaraViz. If you need it, install with 'pip install --pre mesa[viz]'
(2, 4)

AttributeError: 'Firefighter' object has no attribute 'destination'

In [ ]:
result = pd.DataFrame(allGrids)
result

,Steps,VictimsRescued,VictimsLost,NewFire,Dices,DamageTokens,ChangedPOIs
0,0,0,0,[],"{'red': 4, 'black': 5}",0,[]
1,0,0,0,"[{'position': (4, 3), 'state': 'smoke'}]","{'red': 3, 'black': 2}",2,[]
2,0,0,0,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 2}",2,[]
3,0,0,0,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 1}",2,[]
4,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 2}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
5,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
6,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 3}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
7,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
8,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
9,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
10,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
11,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 2}",3,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
12,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 5}",3,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
13,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 3}",3,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
14,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 3}",3,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
15,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 3}",6,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
16,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 5}",6,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
17,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 3}",7,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
18,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 3}",7,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
19,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 0}",8,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
20,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 2}",8,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
21,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 0}",8,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
22,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 2}",11,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
23,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 2}",13,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
24,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 5}",13,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
25,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 0}",16,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
26,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 5}",16,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
27,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 0}",19,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
28,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 5}",19,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
29,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 4}",20,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
30,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 1}",20,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
31,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 0}",20,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
32,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 0}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
33,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 3}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
34,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 4}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
35,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 3}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
36,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 2}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
37,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 1}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
38,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 2}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
39,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 1}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."

In [ ]:
result

,Steps,VictimsRescued,VictimsLost,NewFire,Dices,DamageTokens,ChangedPOIs
0,0,0,0,[],"{'red': 4, 'black': 5}",0,[]
1,0,0,0,"[{'position': (4, 3), 'state': 'smoke'}]","{'red': 3, 'black': 2}",2,[]
2,0,0,0,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 2}",2,[]
3,0,0,0,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 1}",2,[]
4,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 2}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
5,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
6,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 3}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
7,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
8,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
9,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
10,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 0}",2,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
11,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 2}",3,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
12,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 5}",3,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
13,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 3}",3,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
14,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 3}",3,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
15,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 3}",6,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
16,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 5}",6,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
17,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 3}",7,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
18,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 3}",7,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
19,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 0}",8,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
20,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 2}",8,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
21,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 0}",8,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
22,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 2}",11,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
23,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 2}",13,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
24,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 5}",13,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
25,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 0}",16,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
26,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 5}",16,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
27,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 0}",19,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
28,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 5}",19,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
29,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 4}",20,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
30,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 1}",20,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
31,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 0}",20,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
32,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 0}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
33,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 3}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
34,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 4}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
35,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 3}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
36,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 2}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
37,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 1}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
38,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 2}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."
39,0,0,1,"[{'position': (4, 3), 'state': 'smoke'}, {'pos...","{'red': 4, 'black': 1}",23,"[{'position': (2, 4), 'Rescued': False, 'Victi..."