In [1]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
plt.rcParams["animation.html"] = "jshtml"
matplotlib.rcParams['animation.embed_limit'] = 2**128

import numpy as np
import pandas as pd
import seaborn as sns
sns.set()

import time
import datetime

from Models.Fire import Fire
from Models.Firefighter import Firefighter
from Models.FireRescueModel import FireRescueModel

model = FireRescueModel(strategy="intelligent")

ITERATIONS = 100
i = 0

while not(model.defeat()) and not(model.victory()) and i < ITERATIONS:
    model.step()
    i += 1

if (model.victory()):
    print("Players won")
elif (model.defeat()):
    print("Players Lost")
else:
    print("Times up")

print("Damage: ", model.damageTokens)
print("Victims Rescued: ", model.victimsRescued)
print("Victims Lost: ", model.victimsLost)
    
allAgentsInfo = model.datacollector.get_agent_vars_dataframe()
allAgentsInfo.info()

allGrids = model.datacollector.get_model_vars_dataframe()
allGrids.info()

# fig, axs = plt.subplots(figsize = (4, 4))
# axs.set_xticks([])
# axs.set_yticks([])
# patch = plt.imshow(allGrids.iloc[0, 0], cmap = plt.cm.binary)

# def animate(i):
#     patch.set_data(allGrids.iloc[i, 0])

# anim = animation.FuncAnimation(fig, animate, frames = model.steps)

# anim

Could not import SolaraViz. If you need it, install with 'pip install --pre mesa[viz]'
4 :  8 [(2, 0), (2, 1), (3, 1), (4, 1), (5, 1)]
4 :  8 [(2, 1), (3, 1), (4, 1), (5, 1)]
4 :  7 [(3, 1), (4, 1), (5, 1)]
4 :  6 [(4, 1), (5, 1)]
4 :  4 [(5, 1)]
It was not a victim :(
4 :  3 []
1 :  8 [(0, 6), (0, 5), (0, 4), (1, 4), (2, 4)]
1 :  8 [(0, 5), (0, 4), (1, 4), (2, 4)]
1 :  7 [(0, 4), (1, 4), (2, 4)]
1 :  6 [(1, 4), (2, 4)]
1 :  3 [(2, 4)]
Found a Victim at  (2, 4) !
1 :  2 []
0 :  8 [(6, 1), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5)]
0 :  8 [(7, 1), (7, 2), (7, 3), (7, 4), (7, 5)]
0 :  7 [(7, 2), (7, 3), (7, 4), (7, 5)]
0 :  4 [(7, 3), (7, 4), (7, 5)]
0 :  3 [(7, 4), (7, 5)]
0 :  4 [(7, 5)]
Found a Victim at  (7, 5) !
0 :  3 []
Added Damage:  7
Added Damage:  8
Added Damage:  9
Added Damage:  10
1 :  8 [(2, 4), (1, 4), (1, 3), (0, 3)]
1 :  8 [(1, 4), (1, 3), (0, 3)]
1 :  6 [(1, 3), (0, 3)]
1 :  8 [(1, 3), (0, 3)]
0 :  8 [(1, 3), (0, 3)]
0 :  8 [(0, 3)]
Victim Saved:  1
0 :  6 []
1 :  8 [(1, 3), (0, 3)]
1 :  4 [(0, 3)]
Victim Saved:  2
1 :  2 []
Added Damage:  13
Added Damage:  14
Added Damage:  15
Added Damage:  16
Added Damage:  17
Added Damage:  18
Added Damage:  19
Added Damage:  20
Added Damage:  21
Added Damage:  22
Added Damage:  23
Added Damage:  24
Added Damage:  25
Players Lost
Damage:  25
Victims Rescued:  2
Victims Lost:  1
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 216 entries, (np.int64(1), np.int64(5)) to (np.int64(36), np.int64(3))
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Position  216 non-null    object
dtypes: object(1)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Steps           36 non-null     int64
 1   VictimsRescued  36 non-null     int64
 2   VictimsLost     36 non-null     int64
 3   NewFire         36 non-null     object
 4   Dices           36 non-null     object
 5   DamageTokens    36 non-null     int64
 6   ChangedPOIs     36 non-null     object
dtypes: int64(4), object(3)
memory usage: 2.1+ KB

In [2]:
result = pd.DataFrame(allGrids)
result

,Steps,VictimsRescued,VictimsLost,NewFire,Dices,DamageTokens,ChangedPOIs
0,0,0,0,[],"{'red': 1, 'black': 2}",0,[]
1,0,0,0,"[{'position': (6, 5), 'state': 'smoke'}]","{'red': 3, 'black': 4}",6,[]
2,0,0,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 4}",6,[]
3,0,0,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 4}",10,[]
4,0,1,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 0}",10,[]
5,0,2,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 4}",12,[]
6,0,2,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 1}",12,[]
7,0,2,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 1}",12,[]
8,0,2,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 5}",12,[]
9,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 2}",12,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
10,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 5}",15,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
11,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 3}",15,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
12,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 2}",15,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
13,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 4}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
14,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 1}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
15,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 5}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
16,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 2}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
17,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 4}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
18,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 5}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
19,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 1}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
20,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 1}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
21,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 2}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
22,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 5}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
23,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 1}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
24,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 3}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
25,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 0}",18,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
26,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 1}",18,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
27,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 4}",19,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
28,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 0}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
29,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 0}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
30,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 4}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
31,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 3}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
32,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 4}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
33,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 4}",22,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
34,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 5}",22,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
35,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 4}",23,"[{'position': (7, 5), 'Rescued': False, 'Victi..."

In [3]:
result

,Steps,VictimsRescued,VictimsLost,NewFire,Dices,DamageTokens,ChangedPOIs
0,0,0,0,[],"{'red': 1, 'black': 2}",0,[]
1,0,0,0,"[{'position': (6, 5), 'state': 'smoke'}]","{'red': 3, 'black': 4}",6,[]
2,0,0,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 4}",6,[]
3,0,0,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 4}",10,[]
4,0,1,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 0}",10,[]
5,0,2,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 4}",12,[]
6,0,2,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 1}",12,[]
7,0,2,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 1}",12,[]
8,0,2,0,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 5}",12,[]
9,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 2}",12,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
10,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 5}",15,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
11,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 3}",15,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
12,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 2}",15,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
13,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 4}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
14,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 1}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
15,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 5}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
16,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 2}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
17,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 4}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
18,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 5}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
19,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 1}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
20,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 1}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
21,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 2}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
22,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 6, 'black': 5}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
23,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 1}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
24,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 3}",17,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
25,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 0}",18,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
26,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 7, 'black': 1}",18,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
27,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 4}",19,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
28,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 0, 'black': 0}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
29,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 5, 'black': 0}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
30,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 4}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
31,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 3}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
32,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 2, 'black': 4}",20,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
33,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 1, 'black': 4}",22,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
34,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 5}",22,"[{'position': (7, 5), 'Rescued': False, 'Victi..."
35,0,2,1,"[{'position': (6, 5), 'state': 'smoke'}, {'pos...","{'red': 3, 'black': 4}",23,"[{'position': (7, 5), 'Rescued': False, 'Victi..."